### ISSUE TITLE
Package incompatible projects with older versions of "Microsoft.Extensions.Configuration"

### ISSUE THREAD

**Issue by phillip-mofadeng** [mrhuo/MrHuo.OAuth#11]
Due to the dependency on  "Microsoft.Extensions.Configuration" Version="5.0.0", package has reference confilicts with packages and projects that depend on older versions of Microsoft.Extensions.Configuration.

**Comment by mrhuo** [comment]
thanks this idea, next version will remove "Microsoft.Extensions.Configuration" dependency
