### ISSUE TITLE
GiteeUserModel中默认不带唯一标识Id吗？

### ISSUE THREAD

**Issue by kinglinggo** [mrhuo/MrHuo.OAuth#16]

**Comment by coolqingcheng** [comment]
GitHub登录也获取不到唯一Id。。。。
感觉登录了个寂寞

**Comment by coolqingcheng** [comment]
看样子这个库没有更新了，自己fork一份，改一下对应的UserInfoModel就行了，加一个Id

**Comment by mrhuo** [comment]
> 看样子这个库没有更新了，自己fork一份，改一下对应的UserInfoModel就行了，加一个Id

抱歉，近一年来经历了很多人生难题，导致这个库一直停滞不前。您可以 PR 您修改后的代码，感谢您的贡献和使用！！
