### ISSUE TITLE
微信登录提示必须在微信客户端中打开。

### ISSUE THREAD

**Issue by mrt3389** [mrhuo/MrHuo.OAuth#2]
如题，提示必须在微信客户端中打开，如果是pc应用的话，就不能用啦。

**Comment by mrhuo** [comment]
对的，现在接入这个微信是微信公众号登录，微信公众号登陆，必须在微信客户端中。
你说的PC应用那种是微信开发者平台登录，这个在计划中

**Comment by mrhuo** [comment]
@mrt8544 你好，已对接微信公众平台扫码登录组件，但是需要 appid 做测试，等待测试完毕之后即可正常使用。
