### ISSUE TITLE
工程结构建议

### ISSUE THREAD

**Issue by ye4241** [mrhuo/MrHuo.OAuth#4]
采用比较好的层级结构的，外部只有src和docs两个目录，如果需要的话，可以保留samples（但是目测这个也不需要sample的），然后将源码挪到src的，docs下面就是readme需要涉及到的图标的。
以及增加develop分支，并做判断如果合并到main分支自动分发到nuget的吧。

可以参考一下隔壁的 https://github.com/MahApps/MahApps.Metro

**Comment by mrhuo** [comment]
赞，真需要改造一下的，谢谢。

**Comment by mrhuo** [comment]
@ye4241  已经将代码目录整理，项目代码全部移入 src 目录，其他目录慢慢建立。再次感谢！
