### ISSUE TITLE
github插件无法获取到正确的用户名

### ISSUE THREAD

**Issue by nygula** [mrhuo/MrHuo.OAuth#5]
userInfo: {
name: null
avatar_url: "https://avatars2.githubusercontent.com/u/13066114?v=4"
email: null
company: null
blog: ""
bio: null
created_at: "2015-06-26T14:34:54Z"
updated_at: "2021-01-19T05:27:12Z"
public_repos: 148
public_gists: 1
followers: 2
following: 0
message: null
}

**Comment by mrhuo** [comment]
你好，能提供一下日志嘛？使用 console 启动时，日志会输出到 console 里，看下日志。肯定有出错的地方。

**Comment by nygula** [comment]
`**info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: D:\cscode\Charlotte\Charlotte.Oauth
POST [https://github.com/login/oauth/access_token]
POST [grant_type]=[authorization_code]
POST [code]=[4bba7229100aacd0ce4fee]
POST [client_id]=[84038176133a951970d0b]
POST [client_secret]=[7dae364d3c4a2fc9fceaa08c4a2fedfe5c9254a2e5]
POST [redirect_uri]=[https://localhost:5001/oauth/githubcallback]
POST Header [accept]=[application/json]
POST Header [User-Agent]=[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.66]
POST [https://github.com/login/oauth/access_token], reponse=[{"access_token":"6354b3bf21793325a4aa86f6294e373abdfb1651b0","token_type":"bearer","scope":"repo"}]
GET [https://api.github.com/user]
GET Header [Authorization]=[token 6354b3bf21793325a4AA86f6294e373abdfb1651b0]
GET Header [accept]=[application/json]
GET Header [User-Agent]=[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.66]
GET [https://api.github.com/user?access_token=6354b3bf21793325a4aa86f6294e373abdfb1651b0], reponse=[{
  "login": "nygula",
  "id": 13066114,
  "node_id": "MDQ6VXNlcjEzMDY2MTE0",
  "avatar_url": "https://avatars2.githubusercontent.com/u/13066114?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/nygula",
  "html_url": "https://github.com/nygula",
  "followers_url": "https://api.github.com/users/nygula/followers",
  "following_url": "https://api.github.com/users/nygula/following{/other_user}",
  "gists_url": "https://api.github.com/users/nygula/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/nygula/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/nygula/subscriptions",
  "organizations_url": "https://api.github.com/users/nygula/orgs",
  "repos_url": "https://api.github.com/users/nygula/repos",
  "events_url": "https://api.github.com/users/nygula/events{/privacy}",
  "received_events_url": "https://api.github.com/users/nygula/received_events",
  "type": "User",
  "site_admin": false,
  "name": null,
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 148,
  "public_gists": 1,
  "followers": 2,
  "following": 0,
  "created_at": "2015-06-26T14:34:54Z",
  "updated_at": "2021-01-19T06:15:43Z"
}
]
`

**Comment by nygula** [comment]
{
isSccess: true
errorMessage: null
accessToken: {
token_type: "bearer"
access_token: "6354b3bf21793325a486f6294e373abdfb1651b0"
refresh_token: null
scope: "repo"
expires_in: null
error: null
error_description: null
}
userInfo: {
name: null
avatar_url: "https://avatars2.githubusercontent.com/u/13066114?v=4"
email: null
company: null
blog: ""
bio: null
created_at: "2015-06-26T14:34:54Z"
updated_at: "2021-01-19T06:15:43Z"
public_repos: 148
public_gists: 1
followers: 2
following: 0
message: null
}
}

**Comment by mrhuo** [comment]
看到了，是 github 接口返回的数据就是 null，看下面的代码，这个我来看下文档处理一下。

```
{
	"login": "nygula",
	"id": 13066114,
	"node_id": "MDQ6VXNlcjEzMDY2MTE0",
	"avatar_url": "https://avatars2.githubusercontent.com/u/13066114?v=4",
	"gravatar_id": "",
	"url": "https://api.github.com/users/nygula",
	"html_url": "https://github.com/nygula",
	"followers_url": "https://api.github.com/users/nygula/followers",
	"following_url": "https://api.github.com/users/nygula/following{/other_user}",
	"gists_url": "https://api.github.com/users/nygula/gists{/gist_id}",
	"starred_url": "https://api.github.com/users/nygula/starred{/owner}{/repo}",
	"subscriptions_url": "https://api.github.com/users/nygula/subscriptions",
	"organizations_url": "https://api.github.com/users/nygula/orgs",
	"repos_url": "https://api.github.com/users/nygula/repos",
	"events_url": "https://api.github.com/users/nygula/events{/privacy}",
	"received_events_url": "https://api.github.com/users/nygula/received_events",
	"type": "User",
	"site_admin": false,
	"name": null,   <----------- 这里
	"company": null,
	"blog": "",
	"location": null,
	"email": null,
	"hireable": null,
	"bio": null,
	"twitter_username": null,
	"public_repos": 148,
	"public_gists": 1,
	"followers": 2,
	"following": 0,
	"created_at": "2015-06-26T14:34:54Z",
	"updated_at": "2021-01-19T06:15:43Z"
}
```

貌似 `"login": "nygula"` 这个字段可以用，谢谢提出问题，我来解决。

**Comment by mrhuo** [comment]
@nygula 已解决，请使用 `MrHuo.OAuth.Github 1.0.1`

`Install-Package MrHuo.OAuth.Github -Version 1.0.1`
