### ISSUE TITLE
DefaultStateManager

### ISSUE THREAD

**Issue by MickeyShiue** [mrhuo/MrHuo.OAuth#6]
authStates 如果有多台 WebServer，oAuthController 的 DefaultStateManager.Instance().IsStateExists(state) 不會取不到東西嗎?

**Comment by mrhuo** [comment]
你好，谢谢提出问题。这里的 `DefaultStateManager` 只是提供了一个默认内部的字典存储的实现，**不适合** 多台 `web server` 的情况，要想实现也很容易，添加 `IDistributeCache` ，可以用 `redis` 或者其他方式都可以解决。

欢迎提供这方面实例代码。

**Comment by mrhuo** [comment]
可以实现这个类 `IStateManager`，代码：`https://github.com/mrhuo/MrHuo.OAuth/blob/main/MrHuo.OAuth.Core/StateManager/IStateManager.cs`

*工程结构可能以后会改，这个代码文件路径以后可能会改变。*

**Comment by MickeyShiue** [comment]
好的，我找時間實現 redis cache 再發PR給你
